baseURL = "http://example.org/"
languageCode = "en-us"
title = "Jose Hernandez"
theme = "kiera"
copyright = "Copyright &copy; 2020 - Jose Hernandez"

pygmentsCodeFences = true

disqusShortname = "" #Disqus shortname
googleAnalytics = "" #Google Analytics ID

[author]
    name = "Jose Hernandez"           #Author name
    github = "hernandezjose"         #Github username
    # gitlab = ""         #Gitlab username
    linkedin = "josehdz"       #LinkedIn username
    # facebook = ""       #Facebook username
    twitter = "josewhocodes"        #Twitter username
    # instagram = ""      #Instagram username
    # stackoverflow = ""  #StackOverflow username

[params]
    tagline = "Thoughts from Chicagoan turned big data engineer."
    customCSS = []  #Optional Customised CSS

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/blog"
  weight = 1

[[menu.main]]
  identifier = "midtown"
  name = "Midtown"
  url = "/midtown"
  weight = 1
